SneakerUS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static  import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('about/', views.about, name='about'),
    path('product/<int:producto_id>/', views.productDetails, name='details'),
    path('login/', views.auth_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.auth_logout, name='logout'),
    path('customer/<int:customer_id>/', views.profile, name='profile'),
    path('customer/update/delivery/', views.create_update_delivery, name='create_update_delivery'),
    path('customerlist/', views.customer_list, name='customer_list'),
    path('customercreate/', views.customer_create, name='customer_create'),
    path('customerupdate/<int:customer_id>/', views.customer_update, name='customer_update'),
    path('customerdelete/<int:customer_id>/', views.customer_delete, name='customer_delete'),
    path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),
    path('tracking/', views.track_orders, name='track_orders'),
    path('tracking/<str:tracking_id>/', views.track_order, name='track_order'),
    path('review/<str:product_id>/', views.review_order, name='review_order'),
    path('orders/', views.view_orders, name='view_orders'),
    path('order/<int:product_id>/<int:order_id>/claim/', views.claim_product, name='claim_product'),
]

store/models.py
from collections.abc import Iterable
from django.db import models
from django.contrib.auth.models import UserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.validators import MinValueValidator

# Create your models here.

class SneakerUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("El email es obligatorio")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        extra_fields.setdefault("is_admin", False)
        return self._create_user(email, password, **extra_fields)
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_admin", True)
        return self._create_user(email, password, **extra_fields)
    
class SneakerUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name='email', max_length=60, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email' 
    REQUIRED_FIELDS = [] 
    objects = SneakerUserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True
    
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['-date_joined']
    
    

class Customer(models.Model):
    user = models.OneToOneField(SneakerUser, null=True, blank=True, on_delete = models.CASCADE)
    name = models.CharField(max_length=200 , null=False, blank=False)
    email = models.EmailField(max_length=200 , null=True, blank=False)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=50 , null=False, unique=True, blank=False)
    
    def __str__(self):
        return self.name
   
class Color(models.Model):
    name = models.CharField(max_length=20, null=False, unique=True, blank=False)

    def __str__(self):
        return self.name

class Size(models.Model):
    name = models.FloatField(null=False, unique=True)

    def __str__(self):
        return str(self.name)


class ProductColor(models.Model):
    product = models.ForeignKey('Product', null=True, on_delete = models.SET_NULL)
    color = models.ForeignKey('Color', null=True, on_delete = models.SET_NULL)
    
    def __str__(self):
        return str(self.product) + ' ' + str(self.color)

    class Meta:
        verbose_name = 'Product color'
        verbose_name_plural = 'Product colors'
        ordering = ['product', 'color']

class ProductSize(models.Model):
    product = models.ForeignKey('Product', null=True, on_delete = models.SET_NULL)
    size = models.ForeignKey('Size', null=True, on_delete = models.SET_NULL)
    stock = models.IntegerField(default=0, null=False, blank=False, validators=[MinValueValidator(0)])
    
    def __str__(self):
        return str(self.product) + ' ' + str(self.size)

    class Meta:
        verbose_name = 'Product size'
        verbose_name_plural = 'Product sizes'
        ordering = ['product', 'size']

class Product(models.Model):
    name = models.CharField(max_length=200 , null=False, blank=False)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=False, blank=False, validators=[MinValueValidator(0)])
    brand = models.ForeignKey(Brand, null=True, on_delete = models.SET_NULL)
    image = models.ImageField(null=True, blank=True)
    description = models.CharField(max_length=200 , null=True)
    details = models.CharField(max_length=500 , null=True)
    

    
    def __str__(self):
        return self.name
 
class Status(models.Model):
    name = models.CharField(max_length=200 , null=False, unique=True, blank=False)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Status'
        ordering = ['name']

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete = models.SET_NULL)
    address = models.CharField(max_length=200 , null=False, blank=False)
    city = models.CharField(max_length=200 , null=False, blank=False)
    state = models.CharField(max_length=200 , null=False, blank=False)
    zipcode = models.CharField(max_length=200 , null=False, blank=False)
    country = models.CharField(max_length=200 , null=False, blank=False)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.address

    class Meta:
        verbose_name = 'Shipping address'
        verbose_name_plural = 'Shipping addresses'
        ordering = ['-date_added']

class Order(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete = models.SET_NULL)
    date_ordered = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey(Status, null=False, on_delete =models.CASCADE)
    tracking_id=models.CharField(max_length=200 , null=True, unique=True, blank=False)
    fast_delivery = models.BooleanField(default=False, null=True, blank=False)
    shipping_address = models.ForeignKey('ShippingAddress', null=True, on_delete = models.SET_NULL)

    def __str__(self):
        return str(self.id)
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        return sum([item.quantity for item in orderitems])

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        return sum([item.get_total for item in orderitems]) + (5 if self.fast_delivery else 0)
    
class OrderItem(models.Model):
    product_size = models.ForeignKey(ProductSize, null=True, on_delete = models.SET_NULL)
    order = models.ForeignKey(Order, null=True, on_delete = models.SET_NULL)
    quantity = models.IntegerField(default=0, null=True, blank=True, validators=[MinValueValidator(0)])
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        return self.product_size.product.price * self.quantity

class Rating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    comment = models.TextField()

class Claim(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    description = models.TextField()
    date_submitted = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('product', 'order')

    def __str__(self):
        return f'Claim {self.id} by {self.customer.email}'

store/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.validators import validate_email
from .models import Customer, ShippingAddress
from django.core.validators import MinLengthValidator, RegexValidator

class LoginForm(forms.Form):
    email = forms.EmailField(label='Correo Electrónico', required=True)
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput(), required=True)

class RegisterForm(forms.Form):
    name = forms.CharField(label='Nombre Completo', required=True)
    email = forms.EmailField(label='Correo Electrónico', required=True)
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput(), required=True)
    password2 = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput(), required=True)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = get_user_model().objects.filter(email=email)
        if qs.exists():
            self.add_error('email', 'El correo electrónico ya está registrado')
        try:
            validate_email(email)
        except:
            self.add_error('email', 'El correo electrónico no es válido')
        return email
    
    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            self.add_error('password', 'La contraseña debe tener al menos 8 caracteres')
        return password

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')
        if password and password2 and password != password2:
            self.add_error('password2', 'Las contraseñas no coinciden')
    
    
    def save(self, commit=True):
        user = get_user_model().objects.create_user(
            self.cleaned_data.get('email'),
            self.cleaned_data.get('password')
        )
        return user
    
class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'email']
        labels = {
            'name': 'Nombre',
            'email': 'Correo'
        }
    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class ShippingAddressForm(forms.ModelForm):
    zipcode = forms.CharField(label='Código Postal',
    validators=[RegexValidator(r'^\d{5}$', 'El código postal debe contener exactamente 5 dígitos.')])
    class Meta:
        model = ShippingAddress
        fields = ['address', 'city', 'state', 'zipcode', 'country']
        labels = {
            'address': 'Dirección',
            'city': 'Ciudad',
            'state': 'Comunidad Autónoma',
            'country': 'País',
        }

    def __init__(self, *args, **kwargs):
        super(ShippingAddressForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

store/templates/store/about.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<style>
    body {
        font-family: 'Arial', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f9f9f9;
    }

    section {
        max-width: 1200px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    section h2 {
        color: #333;
        font-size: 28px;
        margin-bottom: 20px;
    }

    section p {
        color: #555;
        font-size: 16px;
        line-height: 1.5;
    }

</style>
<section>
    <h2>Bienvenido a la Universidad de Sevilla</h2>
    <p>Quinientos años de historia han convertido a la Universidad de Sevilla en una institución educativa de referencia para el conocimiento en España.</p>
    <p>Gracias a su trayectoria, a su estructura y al equipo humano que le da alma, la Universidad de Sevilla es hoy una referencia en el sistema universitario español y europeo. Los más de 70.000 alumnos matriculados el último curso así lo corroboran, convirtiéndola en la segunda universidad española y la primera andaluza en número de matriculaciones en su centenar de grados y más de 160 másteres. Su compromiso con el conocimiento y la contribución al progreso la hacen destacar también en la generación de patentes, área en el que ostenta el segundo puesto a nivel nacional.</p>
    <p>La US es además una ciudad dentro de la ciudad. Para albergar a todos sus usuarios la Universidad de Sevilla cuenta con uno de los campus más modernos y accesibles, con más de 32 centros y 80.000 m² de instalaciones deportivas. Destaca su servicio de asistencia a la comunidad universitaria que ofrece una atención personalizada para facilitar información y asesoramiento. La universidad es también indispensable para entender la cultura y el patrimonio de Sevilla, pues muchos de sus edificios son esenciales para la riqueza arquitectónica e histórica de la ciudad.</p>
    <p>Podrás encontrarnos en Av. Reina Mercedes, s/n, 41012 Sevilla</p>
    <img src="{% static 'images/logo-US.png' %}" alt="Logo US" style="display: block; margin: auto; width: 279px;">
</section>

{% endblock content %}

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="row">
	<div class="col-lg-12">
		<div class="box-element">
            <a class="btn btn-outline-secondary rounded-3" href="{% url 'store' %}">&#x2190; Continuar Comprando</a>

            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Productos: <strong>{{order.get_cart_items}}</strong></h5></th>
                    <th><h5>Total:<strong> {{order.get_cart_total|floatformat:2}}€</strong></h5></th>
                    <th>
                        <a  style="float:right; margin:5px;" class="btn btn-success rounded-3" href="{% url 'checkout' %}">Finalizar Compra</a>
                    </th>
                </tr>
            </table>
		</div>

		<br>
		<div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Producto</strong></div>
                <div style="flex:1"><strong>Talla</strong></div>
                <div style="flex:1"><strong>Precio</strong></div>
                <div style="flex:1"><strong>Cantidad</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>
            
            {% for item in items %}
            <div class="cart-row">
                
                <div style="flex:2">
                    {% if item.product_size.product.image %}
                    <img class="row-image" src="{{ item.product_size.product.image.url }}">
                    {% else %}
                    <img class="row-image" src="{% static  'images/placeholder.png' %}">
                    {% endif %}
                </div>
                
                <div style="flex:2"><p>{{ item.product_size.product.name }}</p></div>
                <div style="flex:1"><p>{{item.product_size.size.name}}</p></div>
                <div style="flex:1"><p>{{item.product_size.product.price|floatformat:2}}€</p></div>
                <div style="flex:1">
                    <p class="quantity">{{item.quantity}}</p>
                    <div class="quantity">
                        
                        <img data-product="{{item.product_size.product.id}}" data-size="{{item.product_size.size.name}}" 
                        class="chg-quantity update-cart"  
                        data-action="add" data-quantity="1" src="{% static  'images/arrow-up.png' %}">
                
                        <img data-product="{{item.product_size.product.id}}" data-size="{{item.product_size.size.name}}" data-action="remove" 
                        class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                    </div>
                </div>
                <div style="flex:1"><p>{{item.get_total|floatformat:2}}€</p></div>
            </div>
            {% endfor %}
		</div>
	</div>
</div>
<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="row">
     <div class="col-lg-6">
          <div class="box-element" id="form-wrapper">
               <form id="form">
                    {% csrf_token %}
                    <div id="user-info">
                         <div class="form-field ">
                             <input required class="form-control" type="text" name="name" placeholder="Nombre">
                         </div>
                         <div class="form-field">
                             <input required class="form-control" type="email" name="email" placeholder="Correo Electrónico">
                         </div>
                    </div>
                    
                    <div id="shipping-info">
                         <hr>
                         <p>Información de envío:</p>
                         <hr>
                         {% if shippingData %}
                         <div class="form-field">
                              <input class="form-control" type="text" name="address" placeholder="Dirección"
                                   value="{{ shippingData.address }}">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="city" placeholder="Ciudad"
                                   value="{{ shippingData.city }}">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="state" placeholder="Provincia"
                                   value="{{ shippingData.state }}">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="zipcode" placeholder="Código postal"
                                   value="{{ shippingData.zipcode }}">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="country" placeholder="País"
                                   value="{{ shippingData.country }}">
                         </div>
                         {% else %}
                         <div class="form-field">
                              <input class="form-control" type="text" name="address" placeholder="Dirección" value="">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="city" placeholder="Ciudad" value="">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="state" placeholder="Provincia" value="">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="zipcode" placeholder="Código postal" value="">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="country" placeholder="País" value="">
                         </div>
                         {% endif %}
                         <div class="form-field">
                              <input type="checkbox" id="express-delivery" name="express" placeholder="false">
                              <label for="express-delivery">Entrega Express <strong>+5.00€</strong></label>
                         </div>
                         <input type="hidden" id="order-total" value="{{order.get_cart_total|floatformat:2}}">

                    </div>

                    <hr>
                    <input id="form-button" class="btn btn-info btn-block rounded-2" type="submit" value="Continuar" disabled>
               </form>
          </div>

          <br>
          <div class="box-element hidden" id="payment-info">
               
            
                       
               
                    <tr style="margin-top: 15px;">
                         <button id="make-payment" class="btn btn-success rounded-2" style="width: 100%; padding: 15px; margin-bottom: 15px; font-size: 20px; ">Contrarembolso</button>

                         <div id="paypal-button-container"></div>
                         <script src="https://www.paypal.com/sdk/js?client-id=AWZIJZa9rY5wUizrK6KfqFV1HtdfvPkwB30pVJl_ybBn7JMhfz4xMXePPHWk5JKHgKAkX5B3ZXKeCxf1&currency=USD"></script>

                         <script>
                         paypal.Buttons({
                              // Set up the transaction
                              createOrder: function(data, actions) {
                                   var orderTotal = document.getElementById('order-total').value;
                                   var deliveryCost = document.getElementById('express-delivery').checked ? 5.00 : 0.00;
                                   var totalWithDelivery = parseFloat(orderTotal) + parseFloat(deliveryCost);

                                   return actions.order.create({
                                       purchase_units: [{
                                            amount: {
                                               value: totalWithDelivery.toFixed(2)
                                            }
                                        }]
                                    });
                                  },
                                // Finalize the transaction
                                onApprove: function(data, actions) {
                                   return actions.order.capture().then(function(orderData) {
                                        submitFormData();

                                     });
                                  }
                         }).render('#paypal-button-container');
                         </script>
                    </tr>
               </tbody>
               </table>
          </div>
          
     </div>

     <div class="col-lg-6">
          <div class="box-element">
               <a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
               <hr>
               <h3>Resumen del pedido</h3>
               <hr>
               {% for item in items %}
               <div class="cart-row">
                    {% if not item.product_size.product.image %}
                    <div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>
                    {% else %}
                    <div style="flex:2"><img class="row-image" src="{{ item.product_size.product.image.url }}"></div>
                    {% endif %}
                    <div style="flex:2"><b>{{item.product_size.product.name}}</b></div>
                    <div style="flex:2"><p>{{item.product_size.size.name}}</p></div>
                    <div style="flex:1"><p>{{item.product_size.product.price}}€</p></div>
                    <div style="flex:1"><p>x{{item.quantity}}</p></div>
               </div>
               {% endfor %}
               <h5 id="products">Productos:   <strong>{{cartItems}}</strong></h5>
               <h5 id="total">Total:   <strong>{{order.get_cart_total|floatformat:2}}€</strong></h5>
          </div>
     </div>
</div>
<script>

     window.onload = function(){
          document.getElementById('express-delivery').checked = false
          var user = "{{ user }}";
    if (user !== 'AnonymousUser') {
        // Si el usuario está autenticado, llenar automáticamente los campos del formulario
        var username = "{{ request.user.customer.name }}";
        var userEmail = "{{ request.user.email }}";

        document.getElementById('form').name.value = username;
        document.getElementById('form').email.value = userEmail;

        // Deshabilitar los campos ya que están autocompletados
        document.getElementById('user-info').querySelectorAll('input').forEach(function(input) {
            input.disabled = true;
        });
    }
}
     

     if (user != 'AnonymousUser'){
          document.getElementById('user-info').innerHTML = ''
     }

     var form = document.getElementById('form')
     form.addEventListener('submit', function(e){

          if(form.zipcode.value.length != 5){
               alert('El código postal debe tener 5 dígitos')
               e.preventDefault()
               return
          }
          if(form.zipcode.value.match(/^[0-9]+$/) == null){
               alert('El código postal debe contener solo números')
               e.preventDefault()
               return
          }

          e.preventDefault()
          document.getElementById('form-button').classList.add('hidden')
          document.getElementById('payment-info').classList.remove('hidden')
          
     })

     var inputs = document.querySelectorAll('input[type="text"]');
     var submitButton = document.getElementById('form-button');

     inputs.forEach(input => {
          var allFilled = Array.from(inputs).every(input => input.value !== '');
          submitButton.disabled = !allFilled;
     });
     
     inputs.forEach(input => {
          input.addEventListener('input', function() {
               var allFilled = Array.from(inputs).every(input => input.value !== '');
               submitButton.disabled = !allFilled;
          });
     });

     var realTotal = parseFloat("{{order.get_cart_total|floatformat:2}}")
     var delivery = document.getElementById('express-delivery')
     delivery.addEventListener('click', function(e){
          if (delivery.checked == true){
               var modifiedTotal = parseFloat(realTotal + 5.00)
               document.getElementById('total').innerHTML = 'Total:   <strong>' + modifiedTotal + '€</strong>'
               document.getElementById('products').innerHTML = 'Productos:   <strong>{{cartItems}}</strong> + Entrega Express'
          } else {
               document.getElementById('total').innerHTML = 'Total:   <strong>' + realTotal + '€</strong>'
               document.getElementById('products').innerHTML = 'Productos:   <strong>{{cartItems}}</strong>'
          }
     })

     document.getElementById('make-payment').addEventListener('click', function(e){
          submitFormData()
     })

     function submitFormData() {
          var userFormData = {
               'name':null,
               'email':null,
          }
          var shippingInfo = {
               'address':form.address.value,
               'city':form.city.value,
               'state':form.state.value,
               'zipcode':form.zipcode.value,
               'country':form.country.value,
               'fast_delivery':form.express.checked,
          }

          if (user == 'AnonymousUser'){
               userFormData.name = form.name.value
               userFormData.email = form.email.value
          }
          
          var csrftoken = getCookie('csrftoken')
          var url = "{% url 'process_order' %}"
          fetch(url, {
               method:'POST',
               headers:{
                    'Content-Type':'application/json',
                    'X-CSRFToken':csrftoken,
               },
               body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}),
          })
          .then((response) => response.json())
          .then((data) => {
               if (data.error){
                    alert(data.error)
               } else {
                    alert('Pedido realizado con éxito')
                    var cart = getCookie('cart')
                    if (cart){
                         document.cookie = 'cart=' + JSON.stringify({}) + ";domain=;path=/"
                    }
                    window.location.href = "/tracking/" + data.tracking
               }
          })
     }
      
</script>
{% endblock content %}

store/templates/store/customer_form.html
{% extends 'store/main.html' %}

{% block content %}
  <h2>{% if form.instance.pk %}Modificar{% else %}Crear{% endif %} Cliente</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
  </form>
{% endblock %}

store/templates/store/delivery_form.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
<h2>Datos de entrega de {{ customer.name }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock content %}

store/templates/store/profile.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
  <h2>Perfil de {{ customer.name }}</h2>
  <ul>
    <li>Email: {{ customer.email }}</li>
  </ul>

  {% if user.customer.shippingaddress_set.exists %}
    <h3>Datos de entrega:</h3>
    <ul>
      <li>Dirección: {{ user.customer.shippingaddress_set.last.address }}</li>
      <li>Ciudad: {{ user.customer.shippingaddress_set.last.city }}</li>
      <li>Estado: {{ user.customer.shippingaddress_set.last.state }}</li>
      <li>Código postal: {{ user.customer.shippingaddress_set.last.zipcode }}</li>
      <li>País: {{ user.customer.shippingaddress_set.last.country }}</li>
    </ul>
    <a href="{% url 'create_update_delivery' %}" class="btn btn-outline-secondary add-btn">Modificar datos de entrega</a>
  {% else %}
    <a href="{% url 'create_update_delivery' %}" class="btn btn-outline-secondary add-btn">Establecer datos de entrega</a>
  {% endif %}
  <br>
  <br>
{% endblock content %}